version: "3"

#(1)
volumes:
  my_volume:

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      #(2)
      MYSQL_ROOT_PASSWORD: pass
      #(3)
      MYSQL_DATABASE: mydb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: pass
    volumes:
      - my_volume:/var/lib/mysql #(4)

  php:
    image: taroyabuki/php-pdo:7.2 #(5)
    restart: always
    environment:
      MYSQL_SERVER: mysql #(6)
    ports:
      - "80:80" #(7)
    volumes:
      - ./htdocs:/var/www/html #(8)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" #(9)
    environment:
      PMA_HOST: mysql #(10)
#      PMA_USER: root
#      PMA_PASSWORD: pass
